In [3]:
import numpy as np
np.random.randint(1,11) #取出來的亂數不包括11

8

In [4]:
import numpy as np
np.random.randint(50,101,size=(50,5)) #size(列，欄)

array([[ 92,  51,  87,  81,  54],
       [ 84,  79,  86,  57,  70],
       [ 93,  98,  94,  72,  94],
       [ 54,  92,  92,  84,  95],
       [ 72,  87,  59,  99,  54],
       [ 85,  80,  53,  98,  80],
       [ 91,  69,  74,  53,  78],
       [ 87,  82,  68,  73,  99],
       [ 83,  75,  89,  86,  62],
       [ 89,  89,  63,  85,  77],
       [ 73,  78,  58,  99,  72],
       [ 74,  67,  92,  62,  88],
       [ 94,  51,  57,  96,  80],
       [ 99,  72,  82,  93,  94],
       [ 60,  62,  64,  85,  97],
       [ 82,  91,  99,  93,  68],
       [ 68,  80,  66,  88,  95],
       [ 66,  55, 100,  51,  64],
       [ 69,  54,  61,  90,  97],
       [100,  68,  88,  72,  69],
       [ 59, 100,  96,  88,  59],
       [ 79,  52,  79,  87,  84],
       [ 55,  60,  87, 100,  70],
       [100,  89,  77,  53,  84],
       [ 71,  63,  92,  66,  94],
       [ 99,  87,  54,  88,  65],
       [ 84,  89,  59,  87,  72],
       [ 58,  60,  76,  71,  78],
       [ 77,  59,  60,  89,  55],
       [ 80,  64, 100,  89,  98],
       [ 77,  59,  93,  80,  79],
       [ 84,  68,  95,  94,  63],
       [ 55,  58,  71,  71,  79],
       [ 91,  60,  90,  84,  94],
       [ 61,  92, 100,  89,  57],
       [ 86,  89,  67,  69,  78],
       [ 90,  70,  95,  50,  81],
       [ 79,  51,  66,  73,  97],
       [ 92,  72,  61,  88,  58],
       [ 92, 100,  53,  90,  84],
       [ 90,  54,  63,  96,  64],
       [ 66,  87,  73,  53,  61],
       [ 68,  84,  80,  61,  85],
       [ 55,  52,  54,  63,  98],
       [ 62,  91,  83,  98,  57],
       [ 97,  95,  97,  90,  73],
       [ 58,  66,  85,  76,  71],
       [ 87,  82,  97,  91,  76],
       [ 55,  79,  68,  95,  87],
       [ 51,  50,  76,  57,  73]])

In [5]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index = range(1,51)
            )
scores_pd

     國文   英文  數學   地理   歷史
1    80   50  70   62   87
2    90   68  84   58   52
3    89   63  66   94   99
4    58   96  76   71   55
5    58   77  51  100   62
6    67   93  62   52   89
7    95   94  99   56   58
8    55   53  98   80   83
9    98   70  74   64   78
10   64   75  54   51   71
11   63   55  79   91   50
12   55   50  63   51   84
13   57   60  80   59   72
14   94   80  90   91   90
15   62   78  92   97   64
16   78   60  70   91   76
17   70   87  52   65   70
18   57   59  90   78   71
19   85   76  86   55   93
20   98   72  95   89   81
21   98   97  86   67   73
22   88   56  83   53   79
23   99   62  66   62   87
24  100   99  75   63   60
25   69   98  76   55   93
26   77   61  96   90   65
27   78   78  91   80   82
28   91   80  60   92   50
29   83   78  57   52   66
30   53   61  66   50   96
31   76   94  52   71   84
32   83   94  61   92   63
33   77   95  51   81   74
34   50   97  52   97   52
35   62   64  57   55   81
36   76   96  90   74   88
37   66  100  98   56   99
38   67   67  78   52   55
39   84   62  74   59   88
40   99   59  88   92   54
41   65   79  52   75   90
42   60   95  75   74   50
43   64   86  93   88   99
44   96   79  72   75   80
45   77   60  91   68   80
46   51   91  79   73   65
47   70   72  80   91   72
48   76   55  99   93  100
49   61   67  96   86   86
50   68   77  76   77   75

In [6]:
scores_pd.index.name='學號'
scores_pd.columns.name='科目'
scores_pd

科目   國文   英文  數學   地理   歷史
學號
1    80   50  70   62   87
2    90   68  84   58   52
3    89   63  66   94   99
4    58   96  76   71   55
5    58   77  51  100   62
6    67   93  62   52   89
7    95   94  99   56   58
8    55   53  98   80   83
9    98   70  74   64   78
10   64   75  54   51   71
11   63   55  79   91   50
12   55   50  63   51   84
13   57   60  80   59   72
14   94   80  90   91   90
15   62   78  92   97   64
16   78   60  70   91   76
17   70   87  52   65   70
18   57   59  90   78   71
19   85   76  86   55   93
20   98   72  95   89   81
21   98   97  86   67   73
22   88   56  83   53   79
23   99   62  66   62   87
24  100   99  75   63   60
25   69   98  76   55   93
26   77   61  96   90   65
27   78   78  91   80   82
28   91   80  60   92   50
29   83   78  57   52   66
30   53   61  66   50   96
31   76   94  52   71   84
32   83   94  61   92   63
33   77   95  51   81   74
34   50   97  52   97   52
35   62   64  57   55   81
36   76   96  90   74   88
37   66  100  98   56   99
38   67   67  78   52   55
39   84   62  74   59   88
40   99   59  88   92   54
41   65   79  52   75   90
42   60   95  75   74   50
43   64   86  93   88   99
44   96   79  72   75   80
45   77   60  91   68   80
46   51   91  79   73   65
47   70   72  80   91   72
48   76   55  99   93  100
49   61   67  96   86   86
50   68   77  76   77   75

In [20]:
display(scores_pd['國文'][:10])
scores_pd['數學'][:10]
scores_pd.info()

學號
1     80
2     90
3     89
4     58
5     58
6     67
7     95
8     55
9     98
10    64
Name: 國文, dtype: int32

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   國文      50 non-null     int32
 1   英文      50 non-null     int32
 2   數學      50 non-null     int32
 3   地理      50 non-null     int32
 4   歷史      50 non-null     int32
 5   總分      50 non-null     int64
 6   平均      50 non-null     float64
dtypes: float64(1), int32(5), int64(1)
memory usage: 1.9 KB

In [19]:
scores_pd['國文'][:10] + scores_pd['數學'][:10]

學號
1     150
2     174
3     155
4     134
5     109
6     129
7     194
8     153
9     172
10    118
dtype: int32

In [21]:
scores_pd['國文'] + scores_pd['英文'] + scores_pd['地理'] + scores_pd['歷史'] + scores_pd['數學']

學號
1     349
2     352
3     411
4     356
5     348
6     363
7     402
8     369
9     384
10    315
11    338
12    303
13    328
14    445
15    393
16    375
17    344
18    355
19    395
20    435
21    421
22    359
23    376
24    397
25    391
26    389
27    409
28    373
29    336
30    326
31    377
32    393
33    378
34    348
35    319
36    424
37    419
38    319
39    367
40    392
41    361
42    354
43    430
44    402
45    376
46    359
47    385
48    423
49    396
50    373
dtype: int32

In [ ]:
#axis：軸
#axis=0：由上而下開始計算
#axis=1：由左而右開始計算

In [18]:
#統計的實體方法：sum()
scores_pd['總分'] = scores_pd[['國文','英文','數學','地理','歷史']].sum(axis=1)
scores_pd
scores_pd['平均'] = scores_pd[['國文','英文','數學','地理','歷史']].mean(axis=1) #mean：平均
scores_pd

科目   國文   英文  數學   地理   歷史   總分    平均
學號
1    80   50  70   62   87  349  69.8
2    90   68  84   58   52  352  70.4
3    89   63  66   94   99  411  82.2
4    58   96  76   71   55  356  71.2
5    58   77  51  100   62  348  69.6
6    67   93  62   52   89  363  72.6
7    95   94  99   56   58  402  80.4
8    55   53  98   80   83  369  73.8
9    98   70  74   64   78  384  76.8
10   64   75  54   51   71  315  63.0
11   63   55  79   91   50  338  67.6
12   55   50  63   51   84  303  60.6
13   57   60  80   59   72  328  65.6
14   94   80  90   91   90  445  89.0
15   62   78  92   97   64  393  78.6
16   78   60  70   91   76  375  75.0
17   70   87  52   65   70  344  68.8
18   57   59  90   78   71  355  71.0
19   85   76  86   55   93  395  79.0
20   98   72  95   89   81  435  87.0
21   98   97  86   67   73  421  84.2
22   88   56  83   53   79  359  71.8
23   99   62  66   62   87  376  75.2
24  100   99  75   63   60  397  79.4
25   69   98  76   55   93  391  78.2
26   77   61  96   90   65  389  77.8
27   78   78  91   80   82  409  81.8
28   91   80  60   92   50  373  74.6
29   83   78  57   52   66  336  67.2
30   53   61  66   50   96  326  65.2
31   76   94  52   71   84  377  75.4
32   83   94  61   92   63  393  78.6
33   77   95  51   81   74  378  75.6
34   50   97  52   97   52  348  69.6
35   62   64  57   55   81  319  63.8
36   76   96  90   74   88  424  84.8
37   66  100  98   56   99  419  83.8
38   67   67  78   52   55  319  63.8
39   84   62  74   59   88  367  73.4
40   99   59  88   92   54  392  78.4
41   65   79  52   75   90  361  72.2
42   60   95  75   74   50  354  70.8
43   64   86  93   88   99  430  86.0
44   96   79  72   75   80  402  80.4
45   77   60  91   68   80  376  75.2
46   51   91  79   73   65  359  71.8
47   70   72  80   91   72  385  77.0
48   76   55  99   93  100  423  84.6
49   61   67  96   86   86  396  79.2
50   68   77  76   77   75  373  74.6

In [27]:
scores_pd['排名'] = scores_pd['總分'].rank(method='min',ascending=False)
scores_pd

科目   國文   英文  數學   地理   歷史   總分    平均    排名
學號
1    80   50  70   62   87  349  69.8  39.0
2    90   68  84   58   52  352  70.4  38.0
3    89   63  66   94   99  411  82.2   8.0
4    58   96  76   71   55  356  71.2  35.0
5    58   77  51  100   62  348  69.6  40.0
6    67   93  62   52   89  363  72.6  31.0
7    95   94  99   56   58  402  80.4  10.0
8    55   53  98   80   83  369  73.8  29.0
9    98   70  74   64   78  384  76.8  21.0
10   64   75  54   51   71  315  63.0  49.0
11   63   55  79   91   50  338  67.6  43.0
12   55   50  63   51   84  303  60.6  50.0
13   57   60  80   59   72  328  65.6  45.0
14   94   80  90   91   90  445  89.0   1.0
15   62   78  92   97   64  393  78.6  15.0
16   78   60  70   91   76  375  75.0  26.0
17   70   87  52   65   70  344  68.8  42.0
18   57   59  90   78   71  355  71.0  36.0
19   85   76  86   55   93  395  79.0  14.0
20   98   72  95   89   81  435  87.0   2.0
21   98   97  86   67   73  421  84.2   6.0
22   88   56  83   53   79  359  71.8  33.0
23   99   62  66   62   87  376  75.2  24.0
24  100   99  75   63   60  397  79.4  12.0
25   69   98  76   55   93  391  78.2  18.0
26   77   61  96   90   65  389  77.8  19.0
27   78   78  91   80   82  409  81.8   9.0
28   91   80  60   92   50  373  74.6  27.0
29   83   78  57   52   66  336  67.2  44.0
30   53   61  66   50   96  326  65.2  46.0
31   76   94  52   71   84  377  75.4  23.0
32   83   94  61   92   63  393  78.6  15.0
33   77   95  51   81   74  378  75.6  22.0
34   50   97  52   97   52  348  69.6  40.0
35   62   64  57   55   81  319  63.8  47.0
36   76   96  90   74   88  424  84.8   4.0
37   66  100  98   56   99  419  83.8   7.0
38   67   67  78   52   55  319  63.8  47.0
39   84   62  74   59   88  367  73.4  30.0
40   99   59  88   92   54  392  78.4  17.0
41   65   79  52   75   90  361  72.2  32.0
42   60   95  75   74   50  354  70.8  37.0
43   64   86  93   88   99  430  86.0   3.0
44   96   79  72   75   80  402  80.4  10.0
45   77   60  91   68   80  376  75.2  24.0
46   51   91  79   73   65  359  71.8  33.0
47   70   72  80   91   72  385  77.0  20.0
48   76   55  99   93  100  423  84.6   5.0
49   61   67  96   86   86  396  79.2  13.0
50   68   77  76   77   75  373  74.6  27.0

In [28]:
scores_pd.sort_values(by='排名') #排序 buy='欄位名稱'

科目   國文   英文  數學   地理   歷史   總分    平均    排名
學號
14   94   80  90   91   90  445  89.0   1.0
20   98   72  95   89   81  435  87.0   2.0
43   64   86  93   88   99  430  86.0   3.0
36   76   96  90   74   88  424  84.8   4.0
48   76   55  99   93  100  423  84.6   5.0
21   98   97  86   67   73  421  84.2   6.0
37   66  100  98   56   99  419  83.8   7.0
3    89   63  66   94   99  411  82.2   8.0
27   78   78  91   80   82  409  81.8   9.0
7    95   94  99   56   58  402  80.4  10.0
44   96   79  72   75   80  402  80.4  10.0
24  100   99  75   63   60  397  79.4  12.0
49   61   67  96   86   86  396  79.2  13.0
19   85   76  86   55   93  395  79.0  14.0
15   62   78  92   97   64  393  78.6  15.0
32   83   94  61   92   63  393  78.6  15.0
40   99   59  88   92   54  392  78.4  17.0
25   69   98  76   55   93  391  78.2  18.0
26   77   61  96   90   65  389  77.8  19.0
47   70   72  80   91   72  385  77.0  20.0
9    98   70  74   64   78  384  76.8  21.0
33   77   95  51   81   74  378  75.6  22.0
31   76   94  52   71   84  377  75.4  23.0
45   77   60  91   68   80  376  75.2  24.0
23   99   62  66   62   87  376  75.2  24.0
16   78   60  70   91   76  375  75.0  26.0
28   91   80  60   92   50  373  74.6  27.0
50   68   77  76   77   75  373  74.6  27.0
8    55   53  98   80   83  369  73.8  29.0
39   84   62  74   59   88  367  73.4  30.0
6    67   93  62   52   89  363  72.6  31.0
41   65   79  52   75   90  361  72.2  32.0
46   51   91  79   73   65  359  71.8  33.0
22   88   56  83   53   79  359  71.8  33.0
4    58   96  76   71   55  356  71.2  35.0
18   57   59  90   78   71  355  71.0  36.0
42   60   95  75   74   50  354  70.8  37.0
2    90   68  84   58   52  352  70.4  38.0
1    80   50  70   62   87  349  69.8  39.0
34   50   97  52   97   52  348  69.6  40.0
5    58   77  51  100   62  348  69.6  40.0
17   70   87  52   65   70  344  68.8  42.0
11   63   55  79   91   50  338  67.6  43.0
29   83   78  57   52   66  336  67.2  44.0
13   57   60  80   59   72  328  65.6  45.0
30   53   61  66   50   96  326  65.2  46.0
35   62   64  57   55   81  319  63.8  47.0
38   67   67  78   52   55  319  63.8  47.0
10   64   75  54   51   71  315  63.0  49.0
12   55   50  63   51   84  303  60.6  50.0

In [30]:
def formate60(v:int): #V：變數，此設定為分數
    if v >= 60:
        return "及格"
    else:
        return "不及格"

scores_pd[['國文','英文','數學','地理','歷史']].style.format(formate60)