In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5))
scores_pd = pd.DataFrame(scores,
             columns=['國文','英文','數學','地理','歷史'],
             index = range(1,51)
            )
scores_pd

     國文   英文   數學   地理   歷史
1    96   56   67   62   61
2    85   57   67   67   72
3    81   71   83   76   66
4    76   83   75   64   87
5    66   80   84   63   98
6    77   56   67   86   61
7    72   65   59   65   97
8    66   70   61   80   69
9    62   62   84   87   65
10   82   59   88   89   61
11   63   50   83   77   91
12   87   81   97   87   69
13   69   73   81   94   67
14   66   66   92   85   68
15   97   78   96   77   63
16   97   88   84   78   78
17   59   81   76   60  100
18   63   99   77   64   76
19   68   85   67   81   72
20   57   53   64   74   91
21   90   75   94   53   57
22   63   69   93   64   75
23   78   88   78   58   74
24   91   62   59   93   55
25   89   99   80   73   84
26   50   67   94   79   63
27   79  100   90   78   69
28   86   94   90   78   51
29   71   99   68   61   53
30   90   53   67   53   84
31   76   80   65   76   69
32   75   68   85   57   79
33   95   58   94   54   92
34   80   91   96   87   91
35   62   62   91   54   90
36   68   93   72   51   83
37   53   60   70   92   70
38   58   55  100   76   76
39   66   81  100   88   72
40   82   69   79  100   89
41   91   69   87   66   57
42   64   72   85   96   96
43   96   76   79   72   53
44   70   59  100   57   53
45   53   56   63   92   89
46   87   69   84   73   76
47  100   72   65   94   96
48   64  100   86   90   51
49   98   76   70   66   62
50   55   68   66   58   90

In [5]:
def callback1(value:pd.Series):
    return pd.Series([value.max(),value.min(),value.median(),value.mean()],index=['最高分','最低分','中間值','平均值'])
#return傳出，傳出後會組合起來

dataFrame1 = scores_pd.apply(callback1)
dataFrame1

         國文      英文      數學     地理      歷史
最高分  100.00  100.00  100.00  100.0  100.00
最低分   50.00   50.00   59.00   51.0   51.00
中間值   75.50   70.50   82.00   76.0   72.00
平均值   75.38   73.06   80.04   74.1   74.22