In [1]:
from pandas_datareader import data as pdr
import yfinance as yf

yf.pdr_override()
data = pdr.get_data_yahoo("2330.TW", start="2020-01-01")
data

[*********************100%%**********************]  1 of 1 completed

             Open   High    Low  Close   Adj Close    Volume
Date
2020-01-02  332.5  339.0  332.5  339.0  310.429047  31754120
2020-01-03  344.0  345.0  335.5  339.5  310.887024  41811268
2020-01-06  333.0  334.5  332.0  332.0  304.019165  45343057
2020-01-07  332.5  333.0  326.5  329.5  301.729797  50879181
2020-01-08  325.0  333.0  325.0  329.5  301.729797  37567748
...           ...    ...    ...    ...         ...       ...
2024-01-12  581.0  588.0  581.0  584.0  584.000000  16496053
2024-01-15  590.0  590.0  585.0  586.0  586.000000  21143076
2024-01-16  581.0  588.0  579.0  580.0  580.000000  27223860
2024-01-17  583.0  584.0  578.0  581.0  581.000000  42592335
2024-01-18  586.0  589.0  585.0  588.0  588.000000  27983627

[986 rows x 6 columns]